### ISSUE TITLE
Spaces should be given (like dashes are)

### ISSUE THREAD

**Issue by cpradio** [kwandrews7/hubot-hangman#1]
We had a word "C A R P A T H I A N ? M O U N T A I N S", for the life of us, it took us a while to realize we just had to guess the whole word to get the space counted.

I think this is a simple enough change, following the guessDash() logic and adding " " to the previous guesses.

**Comment by kwandrews7** [comment]
Thanks for the heads up cpradio, much appreciated. I didn't realize Wordnik would be giving back multiple words. I created this package off an old script that had basically been abandoned so finding bugs like this just requires me to run across them by coincidence like the "-". I"ll get that fixed this week for you.

**Comment by kwandrews7** [comment]
Fixed @cpradio
Sorry for the delay in getting it pushed. Been a bit busy the past few weeks. Enjoy!
